server:
  port: 8050

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC driver
    url: jdbc:mysql://localhost:3306/products    # MySQL JDBC URL
    username: root
    password: petitphat1
  jpa:
    hibernate:
      ddl-auto: validate                          # Validation strategy
    database: mysql                               # Specify MySQL as the database
    database-platform: org.hibernate.dialect.MySQL8Dialect  # Hibernate dialect for MySQL 8
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
